#!/bin/bash

set -e
function usage() {
    echo -n \
        "Usage: $(basename "$0")
Publish container images to Elastic Container Registry (ECR).
"
}
if [ -f deploy_config.txt ]; then 
  source deploy_config.txt
else
  echo "Could not find deploy_config.txt"
  exit 1
fi

ECR_REPO=${PROJECT}


rm -rf ${PROJECT} 
git clone --depth 1 ${REPO_TO_DEPLOY} 
cd $PROJECT 

if [[ -z "${GIT_COMMIT}" ]]; then
  echo "Please Specify which commit you would like to deploy for the application" 
  exit 1
fi

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    git checkout "{GIT_COMMIT}"
fi

function amazon_ecr_login() {
    # Retrieves a temporary authorization token that can be used to access
    # Amazon ECR, along with the registry URL.
    export AWS_REGION="us-east-1"
    read -r AUTHORIZATION_TOKEN ECR_REGISTRY \
        <<<"$(aws ecr get-authorization-token --region us-east-1 \
            --output "text" \
            --query "authorizationData[0].[authorizationToken, proxyEndpoint]")"

    # The authorization token is base64 encoded, and we need to strip the
    # protocol from the registry URL.
    AUTHORIZATION_TOKEN="$(echo "${AUTHORIZATION_TOKEN}" | base64 --decode)"
    ECR_REGISTRY="${ECR_REGISTRY##*://}"

    # Authenticate to the ECR registry. The authorization token is presented in
    # the format user:password.
    echo "${AUTHORIZATION_TOKEN##*:}" |
        docker login \
            --username "${AUTHORIZATION_TOKEN%%:*}" \
            --password-stdin "${ECR_REGISTRY}"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        amazon_ecr_login
        docker tag "${ECR_REPO}:${GIT_COMMIT}debug" \
            "${ECR_REGISTRY}/${ECR_REPO}:${GIT_COMMIT}debug"
        docker push "${ECR_REGISTRY}/${ECR_REPO}:${GIT_COMMIT}debug"
    fi
fi

cd ..
rm -rf ${PROJECT} 
